spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.14.202:3306/third_project?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: java
    druid:
      initial-size: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.14.202
    port: 6379
    database: 0
    password: root
    jedis:
      pool:
        min-idle: 5
#  task:
#    scheduling:
#      pool:
#        size: 10
mybatis-plus:
  type-aliases-package: com.javasm
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  reasonable: true
crm:
  tokenInfo:
    expTime: 1800000
    key: 66pvsx01BLwE9EEsWTMRfLodpovakv2ttO8rzOegDow=
  cors:
    path: "/**"
    maxAge: 300000
    origins: ["http://localhost:8088"]
    allowedHeaders: []
    allowedMethods: ["GET","POST","PUT","DELETE","OPTIONS"]
    credentials: true
    exposedHeader: ["admin-token"]

